### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [qiime2/q2-emperor#1]
Following the install directions, I get the following when trying to do a `qiime --plugins`

```
Traceback (most recent call last):
  File "/Users/constantino/miniconda2/envs/q2test/bin/qiime", line 9, in <module>
    load_entry_point('q2cli==0.0.0.dev0', 'console_scripts', 'qiime')()
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 549, in load_entry_point
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 2542, in load_entry_point
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 2202, in load
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 2208, in resolve
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/q2cli/cli.py", line 21, in <module>
    PLUGIN_MANAGER = PluginManager()
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/qiime/sdk/plugin_manager.py", line 21, in __init__
    group='qiime.plugin')]
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/qiime/sdk/plugin_manager.py", line 20, in <listcomp>
    plugins = [e.load() for e in pkg_resources.iter_entry_points(
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 2202, in load
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 2208, in resolve
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/q2_diversity/plugin_setup.py", line 35, in <module>
    plugin.methods.register_markdown('markdown/feature_table_to_pcoa.md')
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/qiime/plugin.py", line 140, in register_markdown
    method = qiime.sdk.Method.from_markdown(markdown_filepath)
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/qiime/sdk/method.py", line 105, in from_markdown
    self._from_markdown(markdown_filepath)
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/qiime/sdk/method.py", line 116, in _from_markdown
    input_types[name] = self._parse_semantic_type(type_expr)
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/qiime/sdk/method.py", line 181, in _parse_semantic_type
    pm = qiime.sdk.PluginManager()
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/qiime/sdk/plugin_manager.py", line 21, in __init__
    group='qiime.plugin')]
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/qiime/sdk/plugin_manager.py", line 20, in <listcomp>
    plugins = [e.load() for e in pkg_resources.iter_entry_points(
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 2202, in load
  File "/Users/constantino/miniconda2/envs/q2test/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 2208, in resolve
ImportError: No module named 'q2_emperor'
```

**Comment by ElDeveloper** [comment]
Thanks for reporting this problem @ConstantinoSchillebeeckx, can you copy/paste the output of pip freeze?

**Comment by ConstantinoSchillebeeckx** [comment]
```
conda==4.0.5
conda-env==2.4.5
pycosat==0.6.1
pycrypto==2.6.1
PyYAML==3.11
requests==2.9.1
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by ElDeveloper** [comment]
Thanks for sending that. I think you need to follow the installation instructions in here:
https://github.com/qiime2/qiime2/wiki/Installing-and-using-QIIME-2

And maybe upgrade to the latest versions of some of these packages, I know a few of them have been changing recently. Not sure why qiime-2 or the qiime types are not listed there, any ideas?

**Comment by ConstantinoSchillebeeckx** [comment]
No dice on trying the QIIME2 install again after upgrading pip.  Running `pip freeez` again gives me:
```
appnope==0.1.0
backports.shutil-get-terminal-size==1.0.0
biom-format==2.1.5
bz2file==0.98
CacheControl==0.11.6
click==6.6
contextlib2==0.5.3
cycler==0.10.0
decorator==4.0.10
emperor==0.9.51.dev0
future==0.15.2
ipykernel==4.3.1
ipymd==0.1.2
ipython==4.2.0
ipython-genutils==0.1.0
ipywidgets==4.1.1
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.3.0
jupyter-console==4.1.1
jupyter-core==4.1.0
lockfile==0.12.2
MarkupSafe==0.23
matplotlib==1.5.1
mistune==0.7.2
natsort==4.0.3
nbconvert==4.2.0
nbformat==4.0.1
nose==1.3.7
notebook==4.2.1
numpy==1.11.0
pandas==0.18.1
path.py==0.0.0
pexpect==4.0.1
pickleshare==0.7.2
ptyprocess==0.5.1
Pygments==2.1.3
pyparsing==2.1.4
python-dateutil==2.5.3
python-frontmatter==0.2.1
pytz==2016.4
PyYAML==3.11
pyzmq==15.2.0
q2-diversity==0.0.0.dev0
q2-emperor==0.0.0.dev0
q2-feature-table==0.0.0.dev0
q2-types==0.0.0.dev0
q2cli==0.0.0.dev0
qiime==2.0.1.dev0
qtconsole==4.2.1
requests==2.10.0
scikit-bio==0.4.2
scipy==0.17.1
seaborn==0.7.1
simplegeneric==0.8.1
six==1.10.0
terminado==0.6
tornado==4.3
traitlets==4.2.1
```

I noticed the error references q2_emperor (with an underscore), yet the list above shows q2-emperor (with a dash).  I'm not familiar enough with all the install processes, but that couldn't be part of the issue could it?

**Comment by ElDeveloper** [comment]
@ConstantinoSchillebeeckx, thanks for pointing this out, I installed from scratch (without using the developer mode) and noticed the same problem, after some looking around it seemed like the problem was a missing `__init__.py`. I just pushed something to master, let me know if this fixes your problem.

**Comment by ConstantinoSchillebeeckx** [comment]
Tried re-installing from scratch with:
```
pip install https://github.com/qiime2/qiime2/archive/master.zip https://github.com/qiime2/q2cli/archive/master.zip --force-reinstall -I
pip install git+https://github.com/biocore/emperor.git@new-api --force-reinstall -I
pip install https://github.com/ElDeveloper/q2-emperor/archive/master.zip --force-reinstall -I
```

And now I'm getting the following when installing q2-emperor:
```
Could not find a version that satisfies the requirement qiime>=2.0.0 (from q2-emperor==0.0.0.dev0) (from versions: 1.7.0.dev0, 1.8.0, 1.9.0, 1.9.1)
No matching distribution found for qiime>=2.0.0 (from q2-emperor==0.0.0.dev0)
```

Furthermore, when calling `qiime --help` I'm getting:
```
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
```

What's the recommend way of re-installing from scratch?

**Comment by ElDeveloper** [comment]
@jairideout @ebolyen, have you guys seen this problem before?

@ConstantinoSchillebeeckx, I'm a bit lost by this error. If you are using conda, I highly recommend that you install these development packages in a new environment. Information on how to do this can be found here:

http://conda.pydata.org/docs/using/envs.html

**Comment by ElDeveloper** [comment]
@ConstantinoSchillebeeckx did you try following this tutorial: https://github.com/qiime2/qiime2/wiki/Installing-and-using-QIIME-2

I just did this from scratch and it worked without a problem, let me know if this doesn't work for you.

**Comment by ConstantinoSchillebeeckx** [comment]
@ElDeveloper - yep, that's the install guide I've been following from the very beginning.

After manually removing all QIIME2 directories and miniconda, I re-installed everything per the install tutorial and everything seems to be working.

Thanks for the continued support!

**Comment by ElDeveloper** [comment]
Hmmm, not sure what happened, but I'm glad it is working for you now.

**Comment by ebolyen** [comment]
I don't think anything has changed in regards to package requirements, so I'm afraid I've not seen that before either. Glad you got it working!
